nh-wsi.window.title:"Termoskanne";
nh-wsi.window.width:1280;
nh-wsi.window.height:720;
nh-wsi.window.x:0;
nh-wsi.window.y:0;
nh-wsi.window.decorated:0;
nh-wsi.window.action:"all";
nh-wsi.window.state:"none";
nh-wsi.window.type:"normal";
tk-core.shell.maxScroll:10000;
tk-core.windows:6;
tk-core.tabs:3;
tk-core.menu.program:1;
tk-core.menu.split:1;
tk-core.menu.append:1;
tk-core.menu.window:0;
tk-core.menu.tab:0;
tk-core.menu.close:1;
tk-core.menu.debug:0;
tk-core.titlebar.on:1;
tk-core.titlebar.background:18,18,18,255;
tk-core.titlebar.foreground:179,179,179,255;
tk-core.topbar:1;
tk-core.sidebar:1;
tk-core.clean:0;
tk-core.highlight:1;
tk-core.footer:1;
tk-gfx.border:1;
tk-gfx.font.size:20; 
tk-gfx.timer.blink:0.5;
tk-gfx.style:0;
tk-gfx.animate:0;
tk-gfx.high_contrast:1;
tk-gfx.color.foreground:225,225,225,255; 
tk-gfx.color.background:44,44,44,255; 
tk-gfx.color.accent:88,88,88,255; 
tk-gfx.color.highlight:255,165,0,255; 
